const express = require('express');
const router = express.Router();
const corsAssets = require('./corsAssets');
const maintenance = require('./api/system/maintenance');
const judgeSocketBridge = require('./api/judge/socketBridge');

router.post('/api/runMaintainceTasks', maintenance.runMaintainceTasks);
router.get('/api/judge/socketFile', judgeSocketBridge.serveFile);
router.get('/cors/xdomain.html', corsAssets.xdomainHtml);
router.get('/cors/xdomain.min.js', corsAssets.xdomainScript);
router.get('/cors/streamsaver/mitm.html', corsAssets.streamSaverMitm);
router.get('/cors/streamsaver/sw.js', corsAssets.streamSaverSw);
router.get('/api/cors/xdomain.html', corsAssets.xdomainHtml);
router.get('/api/cors/xdomain.min.js', corsAssets.xdomainScript);
router.get('/api/cors/streamsaver/mitm.html', corsAssets.streamSaverMitm);
router.get('/api/cors/streamsaver/sw.js', corsAssets.streamSaverSw);

const rabbit = require('./api/content/rabbit');

router.post('/api/rabbit/all', rabbit.all);
router.post('/api/rabbit/add', rabbit.add);
router.post('/api/rabbit/getClickCnt', rabbit.getClickCnt);
router.post('/api/rabbit/getRankInfo', rabbit.getRankInfo);
router.post('/api/rabbit/getClickData', rabbit.getClickData);

const user = require('./api/account/user');
const profileApi = require('./api/account/profile');

router.post('/api/user/login', user.login);
router.post('/api/user/sendLoginEmailCode', user.sendLoginEmailCode);
router.post('/api/user/loginByEmailCode', user.loginByEmailCode);
router.post('/api/user/reg', user.reg);
router.post('/api/user/logout', user.logout);
router.get('/api/user/checkAvailability', user.checkAvailability);
router.post('/api/user/checkAvailability', user.checkAvailability);
router.post('/api/user/sendEmailVerifyCode', user.sendEmailVerifyCode);
router.post('/api/user/setUserEmail', user.setUserEmail);
router.post('/api/user/sendPasswordResetCode', user.sendPasswordResetCode);
router.post('/api/user/resetPasswordByEmail', user.resetPasswordByEmail);
router.post('/api/user/getUserInfo', user.getUserInfo);
router.post('/api/user/getUserPublicInfo', user.getUserPublicInfo);
router.post('/api/user/getUserMeta', profileApi.getUserMeta);
router.post('/api/user/setUserPrivileges', profileApi.setUserPrivileges);
router.post('/api/user/updateUserProfile', profileApi.updateUserProfile);
router.post('/api/user/getUserDetail', profileApi.getUserDetail);
router.post('/api/user/getUserProfile', profileApi.getUserProfile);
router.post('/api/user/getUserSecuritySettings', profileApi.getUserSecuritySettings);
router.post('/api/user/queryAuditLogs', profileApi.queryAuditLogs);
router.post('/api/user/updateUserPassword', profileApi.updateUserPassword);
router.post('/api/user/updateUserSelfEmail', profileApi.updateUserSelfEmail);
router.get('/api/user/searchUser', profileApi.searchUser);
router.post('/api/user/searchUser', profileApi.searchUser);
router.post('/api/user/getUserList', profileApi.getUserList);
router.post('/api/user/setUserMotto', user.setUserMotto);
router.post('/api/user/listSessions', user.listSessions);
router.post('/api/user/revokeSession', user.revokeSession);
router.post('/api/user/updateUserPublicInfo', user.updateUserPublicInfo);
router.post('/api/user/modifyPassword', user.modifyPassword);
router.post('/api/user/listAudits', user.listAudits);

const admin = require('./api/system/admin');
const migration = require('./api/system/migration');

router.post('/api/admin/getUserInfoList', admin.getUserInfoList);
router.post('/api/admin/setBlock', admin.setBlock);
router.post('/api/admin/setBlockBatch', admin.setBlockBatch);
router.post('/api/admin/updateUserInfo', admin.updateUserInfo);
router.post('/api/admin/addAnnouncement', admin.addAnnouncement);
router.post('/api/admin/updateAnnouncement', admin.updateAnnouncement);
router.post('/api/admin/listAuditLog', admin.listAuditLog);
router.post('/api/admin/getUserLoginLog', admin.getUserLoginLog);
router.post('/api/admin/resetPassword', admin.resetPassword);
router.post('/api/admin/getAdminStats', admin.getAdminStats);
router.post('/api/admin/getJudgeMonitor', admin.getJudgeMonitor);
router.post('/api/admin/listJudgeClients', admin.listJudgeClients);
router.post('/api/admin/createJudgeClient', admin.createJudgeClient);
router.post('/api/admin/updateJudgeClient', admin.updateJudgeClient);
router.post('/api/admin/resetJudgeClientKey', admin.resetJudgeClientKey);
router.post('/api/admin/deleteJudgeClient', admin.deleteJudgeClient);
router.post('/api/admin/exportMigration', migration.exportMigration);
router.post('/api/admin/importMigration', migration.importMigration);
router.post('/api/migration/migrateUser', migration.migrateUser);
router.post('/api/migration/queryUserMigrationInfo', migration.queryUserMigrationInfo);

const auth = require('./api/account/roles');
const sessionApi = require('./api/account/session');

router.get('/api/auth/getSessionInfo', sessionApi.getSessionInfo);
router.post('/api/auth/login', sessionApi.login);
router.post('/api/auth/logout', sessionApi.logout);
router.get('/api/auth/checkAvailability', sessionApi.checkAvailability);
router.post('/api/auth/sendEmailVerificationCode', sessionApi.sendEmailVerificationCode);
router.post('/api/auth/register', sessionApi.register);
router.post('/api/auth/resetPassword', sessionApi.resetPassword);
router.post('/api/auth/listUserSessions', sessionApi.listUserSessions);
router.post('/api/auth/revokeUserSession', sessionApi.revokeUserSession);
router.post('/api/auth/listPermissions', auth.listPermissions);
router.post('/api/auth/listRoles', auth.listRoles);
router.post('/api/auth/createRole', auth.createRole);
router.post('/api/auth/updateRole', auth.updateRole);
router.post('/api/auth/deleteRole', auth.deleteRole);
router.post('/api/auth/listUserGrants', auth.listUserGrants);
router.post('/api/auth/setUserRoles', auth.setUserRoles);
router.post('/api/auth/setUserRolesBatch', auth.setUserRolesBatch);
router.post('/api/auth/grantUserPermission', auth.grantUserPermission);
router.post('/api/auth/revokeUserPermission', auth.revokeUserPermission);
router.post('/api/auth/listResourceGrants', auth.listResourceGrants);
router.post('/api/auth/searchUsers', auth.searchUsers);
router.post('/api/auth/searchProblems', auth.searchProblems);
router.post('/api/auth/searchContests', auth.searchContests);

const group = require('./api/account/group');
router.get('/api/group/getGroupMeta', group.getGroupMeta);
router.get('/api/group/searchGroup', group.searchGroup);
router.get('/api/group/getGroupList', group.getGroupList);
router.post('/api/group/getGroupList', group.getGroupList);
router.post('/api/group/searchGroup', group.searchGroup);
router.post('/api/group/createGroup', group.createGroup);
router.post('/api/group/renameGroup', group.renameGroup);
router.post('/api/group/deleteGroup', group.deleteGroup);
router.post('/api/group/getGroupMemberList', group.getGroupMemberList);
router.post('/api/group/addMember', group.addMember);
router.post('/api/group/removeMember', group.removeMember);
router.post('/api/group/setGroupAdmin', group.setGroupAdmin);
router.post('/api/group/listGroupGrants', group.listGroupGrants);
router.post('/api/group/grantGroupPermission', group.grantGroupPermission);
router.post('/api/group/revokeGroupPermission', group.revokeGroupPermission);

const problem = require('./api/problem/core');
const publicProblemApi = require('./api/problem/publicApi');
const problemAi = require('./api/problem/ai');

router.post('/api/problem/createProblem', publicProblemApi.createProblem);
router.post('/api/problem/queryProblemSet', publicProblemApi.queryProblemSet);
router.post('/api/problem/getProblem', publicProblemApi.getProblem);
router.post('/api/problem/updateStatement', publicProblemApi.updateStatement);
router.post('/api/problem/setProblemPermissions', publicProblemApi.setProblemPermissions);
router.post('/api/problem/addProblemFile', publicProblemApi.addProblemFile);
router.post('/api/problem/removeProblemFiles', publicProblemApi.removeProblemFiles);
router.post('/api/problem/downloadProblemFiles', publicProblemApi.downloadProblemFiles);
router.post('/api/problem/renameProblemFile', publicProblemApi.renameProblemFile);
router.post('/api/problem/updateProblemJudgeInfo', publicProblemApi.updateProblemJudgeInfo);
router.post('/api/problem/changeProblemType', publicProblemApi.changeProblemType);
router.post('/api/problem/getProblemList', problem.getProblemList);
router.post('/api/problem/getProblemInfo', problem.getProblemInfo);
router.post('/api/problem/updateProblem', problem.updateProblem);
router.post('/api/problem/getProblemSamples', problem.getProblemSamples);
router.post('/api/problem/updateProblemSamples', problem.updateProblemSamples);
router.post('/api/problem/setProblemPublic', problem.setProblemPublic);
router.post('/api/problem/deleteProblem', problem.deleteProblem);
router.post('/api/problem/getProblemCasePreview', problem.getProblemCasePreview);
router.post('/api/problem/getProblemCaseHealth', problem.getProblemCaseHealth);
router.post('/api/problem/setProblemType', problem.setProblemType);
router.post('/api/problem/saveChecker', problem.saveChecker);
router.post('/api/problem/clearCase', problem.clearCase);
router.post('/api/problem/updateSubtaskId', problem.updateSubtaskId);
router.post('/api/problem/getCase', problem.getCase);
router.post('/api/problem/updateCase', problem.updateCase);
router.get('/api/problem/downloadCase', problem.downloadCase);
router.get('/api/problem/downloadAnswerInputs', problem.downloadAnswerInputs);
router.post('/api/problem/getProblemTags', problem.getProblemTags);
router.post('/api/problem/getAllProblemTags', problem.getAllProblemTags);
router.post('/api/problem/getAllProblemTagsOfAllLocales', problem.getAllProblemTagsOfAllLocales);
router.post('/api/problem/createProblemTag', problem.createProblemTag);
router.post('/api/problem/getProblemTagDetail', problem.getProblemTagDetail);
router.post('/api/problem/updateProblemTag', problem.updateProblemTag);
router.post('/api/problem/deleteProblemTag', problem.deleteProblemTag);
router.post('/api/problem/getProblemPublishers', problem.getProblemPublishers);
router.post('/api/problem/getProblemStat', problem.getProblemStat);
router.post('/api/problem/getProblemFastestSubmission', problem.getProblemFastestSubmission);
router.post('/api/problem/getProblemSol', problem.getProblemSol);
router.post('/api/problem/bindPaste2Problem', problem.bindPaste2Problem);
router.post('/api/problem/createSolutionDraft', problem.createSolutionDraft);
router.post('/api/problem/setSolutionVisibility', problem.setSolutionVisibility);
router.post('/api/problem/unbindSol', problem.unbindSol);
router.post('/api/problem/getProblemAuth', problem.getProblemAuth);
router.post('/api/problem/getAnswerCaseList', problem.getAnswerCaseList);
router.post('/api/problem/createFileAccess', problem.createFileAccess);
router.post('/api/problem/ai/config', problemAi.getConfig);
router.post('/api/problem/ai/saveConfig', problemAi.saveConfig);
router.post('/api/problem/ai/models', problemAi.listModels);
router.post('/api/problem/ai/generate', problemAi.generate);
router.post('/api/problem/ai/startGenerate', problemAi.startGenerate);
router.post('/api/problem/ai/generation', problemAi.getGeneration);
router.post('/api/problem/ai/cancelGeneration', problemAi.cancelGeneration);
router.post('/api/problem/ai/generateStream', problemAi.generateStream);
router.get('/api/problem/ai/generationStream', problemAi.streamGeneration);
router.post('/api/problem/ai/saveStd', problemAi.saveStd);
router.post('/api/problem/ai/saveSolution', problemAi.saveSolution);
router.post('/api/problem/ai/previewData', problemAi.previewData);
router.post('/api/problem/ai/saveData', problemAi.saveData);
router.post('/api/problem/ai/saveJudge', problemAi.saveJudge);
router.get('/api/problem/signedDownloadCase', problem.signedDownloadCase);
router.get('/api/problem/signedDownloadAnswerInputs', problem.signedDownloadAnswerInputs);
router.get('/api/problem/signedDownloadAsset', problem.signedDownloadAsset);
router.get('/api/problem/signedDownloadProblemFile', publicProblemApi.signedDownloadProblemFile);
router.post('/api/problem/signedUploadProblemFile', publicProblemApi.verifySignedProblemFileUpload, publicProblemApi.problemFileUpload.single('file'), publicProblemApi.signedUploadProblemFile);

// Unified judge pipeline (judgeProfile + assets) - see docs/judge-pipeline.md
const judgeProfile = require('./api/problem/judgeProfile');
router.post('/api/problem/getJudgeProfile', judgeProfile.getJudgeProfile);
router.post('/api/problem/getJudgeHealth', judgeProfile.getJudgeHealth);
router.post('/api/problem/getJudgePreset', judgeProfile.getJudgePreset);
router.post('/api/problem/saveJudgeProfile', judgeProfile.saveJudgeProfile);
router.post('/api/problem/listAssets', judgeProfile.listAssets);
router.post('/api/problem/getAsset', judgeProfile.getAsset);
router.post('/api/problem/saveAsset', judgeProfile.saveAsset);
router.post('/api/problem/renameAsset', judgeProfile.renameAsset);
router.get('/api/problem/downloadAsset', judgeProfile.downloadAsset);
router.post('/api/problem/deleteAsset', judgeProfile.deleteAsset);


const fileUpload = require('./api/problem/upload');
router.post('/api/problem/uploadData', fileUpload.caseUpload.single('file'), fileUpload.handleCaseUpload);
router.post('/api/problem/signedUploadData', fileUpload.verifySignedCaseUpload, fileUpload.caseUpload.single('file'), fileUpload.handleCaseUpload);

const judge = require('./api/judge/core');

router.post('/api/judge/submit', judge.submit);
router.post('/api/judge/submitMulti', judge.submitMulti);
router.post('/api/judge/submitAnswer', fileUpload.answerUpload.single('file'), judge.submitAnswer);
router.post('/api/judge/getAnswerFile', judge.getAnswerFile);
router.post('/api/judge/getSubmissionList', judge.getSubmissionList);
router.post('/api/judge/getSubmissionInfo', judge.getSubmissionInfo);
router.post('/api/judge/getSubmissionLog', judge.getSubmissionLog);
router.post('/api/judge/querySubmissionStatistics', judge.querySubmissionStatistics);
router.get('/api/judge/streamSubmission', judge.streamSubmissionInfo);
router.post('/api/judge/downloadSubmissionFile', judge.downloadSubmissionFile);
router.post('/api/judge/setSubmissionPublic', judge.setSubmissionPublic);
router.post('/api/judge/deleteSubmission', judge.deleteSubmission);
router.post('/api/judge/reJudge', judge.reJudge);
router.post('/api/judge/reJudgeBatch', judge.reJudgeBatch);
router.post('/api/judge/reJudgeProblem', judge.reJudgeProblem);
router.post('/api/judge/reJudgeContest', judge.reJudgeContest);
router.post('/api/judge/cancelSubmission', judge.cancelSubmission);
router.post('/api/judge/receiveTask', judge.receiveTask);
router.post('/api/judge/clientHeartbeat', judge.clientHeartbeat);
router.post('/api/judge/getLangs', judge.getLangs);

const submissionApi = require('./api/judge/submissionApi');
router.post('/api/submission/submit', submissionApi.submit);
router.post('/api/submission/querySubmission', submissionApi.querySubmission);
router.post('/api/submission/getSubmissionDetail', submissionApi.getSubmissionDetail);
router.post('/api/submission/downloadSubmissionFile', submissionApi.downloadSubmissionFile);
router.post('/api/submission/querySubmissionStatistics', submissionApi.querySubmissionStatistics);
router.post('/api/submission/rejudgeSubmission', submissionApi.rejudgeSubmission);
router.post('/api/submission/cancelSubmission', submissionApi.cancelSubmission);
router.post('/api/submission/setSubmissionPublic', submissionApi.setSubmissionPublic);
router.post('/api/submission/deleteSubmission', submissionApi.deleteSubmission);

const customRun = require('./api/judge/customRun');
router.post('/api/judge/customRun', customRun.customRun);

const ideProfileRun = require('./api/judge/ideProfileRun');
router.post('/api/ide/problemContext', ideProfileRun.problemContext);
router.post('/api/ide/profileRun', ideProfileRun.profileRun);

const common = require('./api/content/common');
const homepage = require('./api/content/homepage');

router.post('/api/common/getAnnouncementList', common.getAnnouncementList);
router.post('/api/common/getAnnouncementInfo', common.getAnnouncementInfo);
router.post('/api/common/getHomeConfig', common.getHomeConfig);
router.post('/api/common/updateHomeConfig', common.updateHomeConfig);
router.post('/api/common/addPaste', common.addPaste);
router.post('/api/common/getPaste', common.getPaste);
router.post('/api/common/updatePaste', common.updatePaste);
router.post('/api/common/delPaste', common.delPaste);
router.post('/api/common/getPasteList', common.getPasteList);
router.post('/api/common/getHitokoto', common.getHitokoto);
router.get('/api/homepage/getHomepage', homepage.getHomepage);
router.get('/api/homepage/getHomepageSettings', homepage.getHomepageSettings);
router.post('/api/homepage/updateHomepageSettings', homepage.updateHomepageSettings);

const judgeClientApi = require('./api/judge/clients');
router.post('/api/judgeClient/addJudgeClient', judgeClientApi.addJudgeClient);
router.post('/api/judgeClient/deleteJudgeClient', judgeClientApi.deleteJudgeClient);
router.post('/api/judgeClient/resetJudgeClientKey', judgeClientApi.resetJudgeClientKey);
router.get('/api/judgeClient/listJudgeClients', judgeClientApi.listJudgeClients);

const discussion = require('./api/content/discussion');
const discussionPortal = require('./api/content/discussionPortal');
router.post('/api/discussion/getDiscussionList', discussion.getDiscussionList);
router.post('/api/discussion/getDiscussion', discussion.getDiscussion);
router.post('/api/discussion/createDiscussion', discussionPortal.createDiscussion);
router.post('/api/discussion/createDiscussionReply', discussionPortal.createDiscussionReply);
router.post('/api/discussion/queryDiscussion', discussionPortal.queryDiscussion);
router.post('/api/discussion/getDiscussionAndReplies', discussionPortal.getDiscussionAndReplies);
router.post('/api/discussion/addDiscussion', discussion.addDiscussion);
router.post('/api/discussion/updateDiscussion', discussionPortal.updateDiscussion);
router.post('/api/discussion/delDiscussion', discussion.delDiscussion);
router.post('/api/discussion/setDiscussionPublic', discussionPortal.setDiscussionPublic);
router.post('/api/discussion/getReplies', discussion.getReplies);
router.post('/api/discussion/addReply', discussion.addReply);
router.post('/api/discussion/updateReply', discussion.updateReply);
router.post('/api/discussion/updateDiscussionReply', discussionPortal.updateDiscussionReply);
router.post('/api/discussion/deleteDiscussion', discussionPortal.deleteDiscussion);
router.post('/api/discussion/deleteDiscussionReply', discussionPortal.deleteDiscussionReply);
router.post('/api/discussion/delReply', discussion.delReply);
router.post('/api/discussion/setDiscussionReplyPublic', discussionPortal.setDiscussionReplyPublic);
router.post('/api/discussion/toggleReaction', discussion.toggleReaction);

const contest = require('./api/contest/contest');
const contestRating = require('./api/contest/rating');
router.post('/api/contest/createContest', contest.createContest);
router.post('/api/contest/getContestList', contest.getContestList);
router.post('/api/contest/getContestInfo', contest.getContestInfo);
router.post('/api/contest/updateContestInfo', contest.updateContestInfo);
router.post('/api/contest/getPlayerList', contest.getPlayerList);
router.post('/api/contest/addPlayer', contest.addPlayer);
router.post('/api/contest/removePlayer', contest.removePlayer);
router.post('/api/contest/contestReg', contest.contestReg);
router.post('/api/contest/closeContest', contest.closeContest);
router.post('/api/contest/recalculateContestRating', contestRating.recalculateContestRating);
router.post('/api/contest/settleContestRating', contestRating.settleContestRating);
router.post('/api/contest/previewRating', contestRating.previewRating);
router.post('/api/contest/previewContestRatingRebuild', contestRating.previewContestRatingRebuild);
router.post('/api/contest/rebuildContestRatings', contestRating.rebuildContestRatings);
router.post('/api/contest/cleanupStaleContestRatings', contestRating.cleanupStaleContestRatings);
router.post('/api/contest/syncContestRatingCache', contestRating.syncContestRatingCache);
router.post('/api/contest/getRatingSystemStats', contestRating.getRatingSystemStats);
router.post('/api/contest/updateProblemList', contest.updateProblemList);
router.post('/api/contest/getProblemList', contest.getProblemList);
router.post('/api/contest/getPlayerProblemList', contest.getPlayerProblemList);
router.post('/api/contest/getProblemInfo', contest.getProblemInfo);
router.post('/api/contest/submit', contest.submit);
router.post('/api/contest/getSubmissionList', contest.getSubmissionList);
router.post('/api/contest/getLastSubmissionList', contest.getLastSubmissionList);
router.post('/api/contest/getSubmissionInfo', contest.getSubmissionInfo);
router.post('/api/contest/getSubmissionLog', contest.getSubmissionLog);
router.get('/api/contest/streamSubmission', contest.streamSubmissionInfo);
router.post('/api/contest/getRank', contest.getRank);
router.post('/api/contest/getRankAt', contest.getRankAt);
router.post('/api/contest/getParticipantTimeline', contest.getParticipantTimeline);
router.post('/api/contest/setScoreboardReveal', contest.setScoreboardReveal);
router.post('/api/contest/startSystest', contest.startSystest);
const contestHacks = require('./api/contest/hacks');
router.post('/api/contest/getHackTargets', contestHacks.getHackTargets);
router.post('/api/contest/getHackTargetCode', contestHacks.getHackTargetCode);
router.post('/api/contest/submitHack', contestHacks.submitHack);
router.post('/api/contest/getHackList', contestHacks.getHackList);
const contestHealth = require('./api/contest/health');
router.post('/api/contest/checkContest', contestHealth.checkContest);
router.post('/api/contest/getRatingChanges', contestRating.getRatingChanges);
router.post('/api/contest/getUserRatingHistory', contestRating.getUserRatingHistory);
router.post('/api/contest/getSingleUserLastSubmission', contest.getSingleUserLastSubmission);
router.post('/api/contest/getSingleUserProblemSubmission', contest.getSingleUserProblemSubmission);

module.exports = router;
